### ISSUE TITLE
Nest module

### ISSUE THREAD

**Issue by sklin93** [ZhouYanzhao/PRM#8]
Hi Yanzhao,
Thanks for the code! Could you explain how to set up the nest modules? I tried 'nest module list' without prm filter, but it still only gives the three modules under prm instead of all 25 modules. So when I try to run the demo, it gives this error: 'Could not find a Nest module matches query "*pascal_voc_classification".' How to set it up properly?

Thanks!

=====
Reinstalled and solved! thanks

**Comment by ZhouYanzhao** [comment]
Glad your problem is solved 👍

**Comment by ZhangLin-PKU** [comment]
Hi @ZhouYanzhao , I have this problem too. I tried reinstalling and rebooting, but the problem is not solved. By the way, I use win10 system. How can I fix it?

Thanks!

**Comment by ZhouYanzhao** [comment]
Hi @Irene-software ,
Please check https://github.com/ZhouYanzhao/Nest/issues/1 for more installation details.
